package models

case class Vevent(
   uid: Option[String],
   dstamp: Option[String],
   dstart: Option[String],
   dtend: Option[String],
   classProp: Option[String],
   created: Option[String],
   description: Option[String],
   geo: Option[String],
   lastMod: Option[String],
   location: Option[String],
   organizer: Option[String],
   priority: Option[String],
   seq: Option[String],
   status: Option[String],
   summary: Option[String],
   transp: Option[String],
   url: Option[String],
   recurid: Option[String],
   rrule: Option[String],
   duration: Option[String],
   attach: Option[String],
   attendee: Option[String],
   categories: Seq[Option[String]],
   comment: String,
   contact: String,
   exdate: String,
   rstatus: String,
   related: String,
   resources: String,
   rdate: String,
   xProp: String,
   ianaProp: String
 )
